#define PHIDEGRADINFLOAT   0.01745329251 
#define DECEX   2 
#define NUMOFBITSTRIG   20 
#define NUMOFBITSCONSTSin   34 
const int NUMOFBITSTRIGMINCONSTSin = NUMOFBITSCONSTSin-NUMOFBITSTRIG; 
#define BITS4TRIG   7 
const int TWOTOBITS4TRIGMIN1 = pow(2,BITS4TRIG)-1; 
const int ONETONUMOFBITSTRIG = 1 << NUMOFBITSTRIG;

#define BITS4SQRT   14 
const int TWOTOBITS4SQRTMIN1 =  pow(2,BITS4SQRT)-1; 
const int BITS4SQRTMIN1 =  BITS4SQRT-1; 
#define NUMOFBITSVXVYVZ   14 
#define NUMOFBITSINVSQRT   23  
#define NUMOFINTBITSHALF   15 
const int NUMOFIBITSDIFF = NUMOFBITSINVSQRT - NUMOFBITSVXVYVZ;
const int TWOTONUMOFBITSHALFMIN1 = pow(2,NUMOFINTBITSHALF) - 1; 
const int NUMOFBITSREMAINDER = NUMOFBITSTRIG - NUMOFINTBITSHALF; 
const int TWOTONUMBEROFBITSREMAINDERMIN1 = pow(2,NUMOFBITSREMAINDER) - 1; 

#define maxInput   75 
#define minInput   0 
#define f   100

const int phiDegRadTxNUMOFBITSCONSTSin = pow(2,NUMOFBITSCONSTSin)*PHIDEGRADINFLOAT*pow(10,-DECEX)/f;
const int N4sqrt = ((maxInput*maxInput*pow(10,2*DECEX)))*pow(2,-BITS4SQRT) + 1;
int SqrtLookUpTable[3434]; 
int InvSqrtLookUpTable[3434];
